import dotenv from "dotenv";
dotenv.config();

import { connectToDatabase } from "../lib/db";
import Product from "../models/Product";

async function seed() {
  try {
    await connectToDatabase();

    // Clear existing products (optional, can comment this if not needed)
    await Product.deleteMany({});

    // Define 50 eco-friendly products
    const products = [
      {
        name: "Eco Bag",
        description: "Reusable and sustainable bag.",
        price: 199,
        category: "bags",
        inStock: true,
        image: "/images/ecobag.jpg",
        brand: "EcoStyle",
        tag: "Reusable",
        ecoScore: 9.5,
      },
      {
        name: "Bamboo Toothbrush",
        description: "Eco-friendly biodegradable toothbrush.",
        price: 49,
        category: "personal-care",
        inStock: true,
        image: "/images/bamboo-toothbrush.jpg",
        brand: "GreenBrush",
        tag: "Biodegradable",
        ecoScore: 9.2,
      },
      {
        name: "Organic Cotton T-Shirt",
        description: "Soft and sustainable organic cotton.",
        price: 799,
        category: "clothing",
        inStock: true,
        image: "/images/organic-tshirt.jpg",
        brand: "EcoWear",
        tag: "Organic",
        ecoScore: 8.9,
      },
      {
        name: "Reusable Metal Straw",
        description: "Durable stainless steel straw set.",
        price: 99,
        category: "drinkware",
        inStock: true,
        image: "/images/metal-straw.jpg",
        brand: "GreenSip",
        tag: "Zero Waste",
        ecoScore: 9.0,
      },
      {
        name: "Solar Charger",
        description: "Portable solar-powered charger for electronics.",
        price: 1599,
        category: "electronics",
        inStock: true,
        image: "/images/solar-charger.jpg",
        brand: "SunVolt",
        tag: "Renewable",
        ecoScore: 8.7,
      },
      {
        name: "Recycled Notebook",
        description: "Notebook made from 100% recycled paper.",
        price: 129,
        category: "home",
        inStock: true,
        image: "/images/recycled-notebook.jpg",
        brand: "PaperLoop",
        tag: "Recycled",
        ecoScore: 8.5,
      },
      {
        name: "Compostable Plates",
        description: "Biodegradable disposable plates.",
        price: 349,
        category: "food-storage",
        inStock: true,
        image: "/images/compostable-plates.jpg",
        brand: "BioServe",
        tag: "Compostable",
        ecoScore: 9.1,
      },
      {
        name: "Eco Laundry Detergent",
        description: "Plant-based eco-friendly detergent.",
        price: 299,
        category: "home",
        inStock: true,
        image: "/images/eco-detergent.jpg",
        brand: "NatureWash",
        tag: "Plant-based",
        ecoScore: 9.0,
      },
      {
        name: "Reusable Water Bottle",
        description: "Insulated bottle for hot and cold drinks.",
        price: 599,
        category: "drinkware",
        inStock: true,
        image: "/images/reusable-bottle.jpg",
        brand: "HydroLeaf",
        tag: "Reusable",
        ecoScore: 9.3,
      },
      {
        name: "Wooden Hair Brush",
        description: "Eco wooden bristles, anti-static brush.",
        price: 249,
        category: "personal-care",
        inStock: true,
        image: "/images/wooden-brush.jpg",
        brand: "NatureComb",
        tag: "Plastic-Free",
        ecoScore: 8.8,
      },
      {
    name: "Hemp Backpack",
    description: "Durable backpack made from sustainable hemp fibers.",
    price: 1499,
    category: "bags",
    inStock: true,
    image: "/images/hemp-backpack.jpg",
    brand: "HempWear",
    tag: "Sustainable",
    ecoScore: 9.4,
  },
  {
    name: "Cork Wallet",
    description: "Eco-friendly wallet made from cork leather.",
    price: 899,
    category: "accessories",
    inStock: true,
    image: "/images/cork-wallet.jpg",
    brand: "NatureCraft",
    tag: "Biodegradable",
    ecoScore: 9.2,
  },
  {
    name: "Organic Lip Balm",
    description: "Moisturizing lip balm with natural ingredients.",
    price: 199,
    category: "personal-care",
    inStock: true,
    image: "/images/organic-lip-balm.jpg",
    brand: "PureGlow",
    tag: "Organic",
    ecoScore: 9.3,
  },
  {
    name: "Reusable Beeswax Wrap",
    description: "Wrap your food naturally with beeswax wraps.",
    price: 399,
    category: "kitchen",
    inStock: true,
    image: "/images/beeswax-wrap.jpg",
    brand: "EcoWrap",
    tag: "Zero-Waste",
    ecoScore: 9.6,
  },
  {
    name: "Bamboo Cutlery Set",
    description: "Portable bamboo utensils for eco-friendly dining.",
    price: 299,
    category: "kitchen",
    inStock: true,
    image: "/images/bamboo-cutlery.jpg",
    brand: "GreenDine",
    tag: "Reusable",
    ecoScore: 9.5,
  },
  {
    name: "Solar Garden Lights",
    description: "Energy-saving solar-powered garden lights.",
    price: 1299,
    category: "electronics",
    inStock: true,
    image: "/images/solar-garden-lights.jpg",
    brand: "SunBright",
    tag: "Renewable",
    ecoScore: 8.8,
  },
  {
    name: "Natural Deodorant",
    description: "Aluminum-free deodorant made from natural minerals.",
    price: 449,
    category: "personal-care",
    inStock: true,
    image: "/images/natural-deodorant.jpg",
    brand: "FreshAura",
    tag: "Chemical-Free",
    ecoScore: 9.0,
  },
  {
    name: "Recycled Glass Tumbler",
    description: "Handcrafted drinking glass from recycled glass.",
    price: 349,
    category: "drinkware",
    inStock: true,
    image: "/images/recycled-glass.jpg",
    brand: "GlassCycle",
    tag: "Recycled",
    ecoScore: 8.9,
  },
  {
    name: "Organic Cotton Socks",
    description: "Comfortable socks made from certified organic cotton.",
    price: 299,
    category: "clothing",
    inStock: true,
    image: "/images/organic-socks.jpg",
    brand: "EcoStep",
    tag: "Organic",
    ecoScore: 9.1,
  },
  {
    name: "Plant-Based Shampoo",
    description: "Eco-friendly shampoo made from plant extracts.",
    price: 549,
    category: "personal-care",
    inStock: true,
    image: "/images/plant-shampoo.jpg",
    brand: "GreenGlow",
    tag: "Vegan",
    ecoScore: 9.2,
  },
  {
    name: "Biodegradable Phone Case",
    description: "Compostable phone case made from wheat straw.",
    price: 699,
    category: "electronics",
    inStock: true,
    image: "/images/biodegradable-phone-case.jpg",
    brand: "EcoShell",
    tag: "Compostable",
    ecoScore: 9.0,
  },
  {
    name: "Jute Shopping Bag",
    description: "Reusable, strong jute grocery bag.",
    price: 199,
    category: "bags",
    inStock: true,
    image: "/images/jute-shopping-bag.jpg",
    brand: "GreenTote",
    tag: "Reusable",
    ecoScore: 9.4,
  },
  {
    name: "Bamboo Razor",
    description: "Plastic-free razor with bamboo handle.",
    price: 349,
    category: "personal-care",
    inStock: true,
    image: "/images/bamboo-razor.jpg",
    brand: "EarthShave",
    tag: "Plastic-Free",
    ecoScore: 8.9,
  },
  {
    name: "Compost Bin",
    description: "Indoor kitchen compost bin with charcoal filter.",
    price: 799,
    category: "home",
    inStock: true,
    image: "/images/compost-bin.jpg",
    brand: "BioHome",
    tag: "Zero Waste",
    ecoScore: 9.1,
  },
  {
    name: "Reusable Grocery Net Bags",
    description: "Set of 5 mesh produce bags made of organic cotton.",
    price: 299,
    category: "bags",
    inStock: true,
    image: "/images/reusable-net-bags.jpg",
    brand: "EcoPack",
    tag: "Reusable",
    ecoScore: 9.3,
  },
  {
    name: "Solar LED Lantern",
    description: "Solar-powered outdoor camping lantern.",
    price: 649,
    category: "electronics",
    inStock: true,
    image: "/images/solar-led-lantern.jpg",
    brand: "SolarLite",
    tag: "Renewable",
    ecoScore: 8.8,
  },
  {
    name: "Natural Loofah Sponge",
    description: "Organic body scrub loofah for bath and shower.",
    price: 149,
    category: "personal-care",
    inStock: true,
    image: "/images/loofah-sponge.jpg",
    brand: "LoofahLove",
    tag: "Natural",
    ecoScore: 9.2,
  },
  {
    name: "Organic Cotton Baby Swaddle",
    description: "Soft and breathable muslin wrap for babies.",
    price: 599,
    category: "clothing",
    inStock: true,
    image: "/images/baby-swaddle.jpg",
    brand: "PureBaby",
    tag: "Organic",
    ecoScore: 9.4,
  },
  {
    name: "Eco Yoga Mat",
    description: "Non-toxic, biodegradable yoga mat made from natural rubber.",
    price: 1099,
    category: "fitness",
    inStock: true,
    image: "/images/eco-yoga-mat.jpg",
    brand: "ZenMat",
    tag: "Non-toxic",
    ecoScore: 9.1,
  },
  {
    name: "Recycled Fabric Tote",
    description: "Fashionable tote bag made from recycled textiles.",
    price: 349,
    category: "bags",
    inStock: true,
    image: "/images/recycled-fabric-tote.jpg",
    brand: "ReTex",
    tag: "Recycled",
    ecoScore: 8.7,
  },
];

    // Insert products
    await Product.insertMany(products);
    console.log("✅ 50 products seeded successfully.");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
}

seed();
